#!/usr/bin/env bash
#
# Adds the privacy usage descriptions iOS requires before the app may touch the
# camera, photo library, mic, or speech recognition. Without these keys iOS
# terminates the app the moment the web view requests the hardware.
#
# The ios/ directory is generated by `npx cap add ios`, so re-run this after any
# regeneration. Safe to run repeatedly — each key is replaced, not duplicated.
#
#   ./scripts/ios-permissions.sh [path/to/Info.plist]
#
# macOS only (depends on PlistBuddy).
set -euo pipefail

PLIST="${1:-ios/App/App/Info.plist}"
PB=/usr/libexec/PlistBuddy

if [ ! -f "$PLIST" ]; then
  echo "error: no Info.plist at $PLIST — run 'npx cap add ios' first." >&2
  exit 1
fi

set_string() {
  "$PB" -c "Delete :$1" "$PLIST" >/dev/null 2>&1 || true
  "$PB" -c "Add :$1 string $2" "$PLIST"
  echo "  $1"
}

echo "Writing usage descriptions to $PLIST"

# LogMeal.tsx and ProgressPhotos.tsx use <input capture="environment">.
set_string NSCameraUsageDescription \
  "FitNext uses the camera to log meals and progress photos."

# The same components also offer a plain file input for existing shots.
set_string NSPhotoLibraryUsageDescription \
  "FitNext accesses your photos so you can pick an existing meal or progress shot."

# CoachChat.tsx voice input. Speech recognition is a separate grant from the
# mic itself, so both keys are required for one tap of the mic button.
set_string NSMicrophoneUsageDescription \
  "FitNext uses the mic so you can talk to your coach."
set_string NSSpeechRecognitionUsageDescription \
  "FitNext transcribes what you say so your coach can respond."

plutil -lint "$PLIST"
